import 'cat.dart';

final List<Cat> availCats = [
  Cat(
    id: 0001,
    breed: 'Persian Cat',
    cardImage: 'assets/card/persian.png',
    detailedImage: 'assets/detail/persian.png',
    storeLocation: 'Main Street Pet Store',
    price: 250.0,
    age: 2,
    gender: 'Male',
    height: 25.0,
    weight: 5.5,
    color: 'White',
    description: 'Affectionate and gentle, Persians are known for their long, luxurious fur.',
  ),
  Cat(
    id: 0002,
    breed: 'Sphinx Cat',
    cardImage: 'assets/card/sphinx.png',
    detailedImage: 'assets/detail/sphinx.png',
    storeLocation: 'Downtown Pets',
    price: 300.0,
    age: 1,
    gender: 'Female',
    height: 30.0,
    weight: 4.0,
    color: 'Brown',
    description: 'The Sphinx is hairless and has a distinctive appearance, often described as "alien-like".',
  ),
  Cat(
    id: 0003,
    breed: 'Bengal Cat',
    cardImage: 'assets/card/bengal.png',
    detailedImage: 'assets/detail/bengal.png',
    storeLocation: 'Cat Haven',
    price: 400.0,
    age: 3,
    gender: 'Male',
    height: 28.0,
    weight: 6.0,
    color: 'Golden',
    description: 'Bengals are known for their distinctive leopard-like spots and energetic personality.',
  ),
  Cat(
    id: 0004,
    breed: 'Abyssinian Cat',
    cardImage: 'assets/card/abyssinian.png',
    detailedImage: 'assets/detail/abyssinian.png',
    storeLocation: 'Furry Friends',
    price: 350.0,
    age: 2,
    gender: 'Female',
    height: 26.0,
    weight: 5.2,
    color: 'Ruddy',
    description: 'Abyssinians are active, playful, and known for their distinctive "ticked" coat pattern.',
  ),
  Cat(
    id: 0005,
    breed: 'Burmese Cat',
    cardImage: 'assets/card/burmese.png',
    detailedImage: 'assets/detail/burmese.png',
    storeLocation: 'Kitty Korner',
    price: 280.0,
    age: 1,
    gender: 'Male',
    height: 27.0,
    weight: 5.8,
    color: 'Chocolate',
    description: 'Burmese cats are affectionate, social, and known for their striking golden eyes.',
  ),
  Cat(
    id: 0006,
    breed: 'Maltese Cat',
    cardImage: 'assets/card/russian_blue.png',
    detailedImage: 'assets/detail/russian_blue.png',
    storeLocation: 'Blue Cat Emporium',
    price: 320.0,
    age: 2,
    gender: 'Female',
    height: 29.0,
    weight: 5.5,
    color: 'Gray',
    description: 'Russian Blues are intelligent, gentle, and known for their plush, blue-gray coat.',
  )
];

